### ISSUE TITLE
Bug: missing a "scale" property in the image dictionary of LSR file

### ISSUE THREAD

**Issue by JelenaBanjac** [FHPythonUtils/PyLSR#3]
## Bug

- [x] I have read the comment above and have completed each step
- [x] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### Describe the bug
Code line `pylsr.read(file_name_lsr)` was raising the `KeyError "scale"`

### Expected outcome
Simple read of the LSR image.

### Actual outcome
Exception `KeyError "scale"` was raised when `pylsr.read(file_name_lsr)` was called. Breaking at line 113 in `pylsr/__init__.py`.

**Comment by FredHappyface** [comment]
Hi thanks so much for raising this and the pr. I'll give it a proper look in the next week or two and merged ☺️ (probably sooner but depends on free time available)
